stages:
  load_data:
    cmd:  python src/get_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - data/winequality.csv
    outs:
    - data/raw/data.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/data.csv
    - src/get_data.py

    outs:
    - data/processed/train.csv
    - data/processed/test.csv

  train:
    cmd: python src/train.py --config=params.yaml
    deps:
      - src/train.py
      - data/processed/train.csv
      - src/get_data.py
