stages:
  load_data:
    cmd:  python src/get_data.py --config=reports/params.yaml
    deps:
    - src/get_data.py
    - data/winequality.csv
    outs:
    - data/raw/data.csv

  split_data:
    cmd: python src/split_data.py --config=reports/params.yaml
    deps:
    - src/split_data.py
    - data/raw/data.csv
    - src/get_data.py

    outs:
    - data/processed/train.csv
    - data/processed/test.csv

  train:
    cmd: python src/train.py --config=reports/params.yaml
    deps:
      - src/train.py
      - data/processed/train.csv
      - src/get_data.py
    metrics: 
      - reports/params.json:
          cache: false
    outs:
      - models/model.joblib

  # evaluate:
  #   cmd: python src/stage_04_evaluate.py --config=params.yaml
  #   deps:
  #     - src/stage_04_evaluate.py
  #     - artifacts/processed_data/test.csv
  #     - artifacts/saved_models/model.joblib
  #     - src/utils/common_utils.py
  #   params:
  #     - base.target_col
  #     - artifacts.split_data.test_path
  #   metrics: 
  #     - artifacts/report/scores.json:
  #         cache: false
